### ISSUE TITLE
Typo in repo description: `ohauth` should be `oauth`

### ISSUE THREAD

**Issue by JakobMiksch** [osmlab/osm-auth#115]
~~`ohauth`~~ --> `oauth`

see scrennshot below:

![image](https://github.com/osmlab/osm-auth/assets/15704517/90a194a3-62fd-4727-ab92-6c22a7b7a4e2)

**Comment by tyrasd** [comment]
This used to refer to a former dependency of this project: https://github.com/osmlab/ohauth (which was removed with the switch to oauth2 in v2.0, see https://github.com/osmlab/osm-auth/commit/529ca131b6feef9dfdea573ecf14654c3e3a9e12#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L38). Agree that this now obsolete reference should be fixed by updating the repo description. PS: I've found one more occurrence of this in [`package.json`](also in https://github.com/osmlab/osm-auth/blob/v2.1.0/package.json#L10).

//ping @bhousel

**Comment by bhousel** [comment]
Oh yeah thanks for flagging, I'll remove the reference to ohauth.
