### ISSUE TITLE
Old oauth tokens with "" don't work in 2.4.0

### ISSUE THREAD

**Issue by starsep** [osmlab/osm-auth#129]
While using osm-auth 2.3.0
1. Oauth token in local storage is saved when logging in `""`. So value is `"${token}"`.
2. Both `${token}` and `"${token}"` in local storage work when making OSM requests.

In 2.4.0:
1. Oauth token is saved without `""` when logging in. Value is `${token}`.
2. Only `${token}` works. `"${token}"` does not.

User after logging in older version needs to log out and log in again.

I wasn't able to catch this issue when upgrading because I cannot reproduce it with React dev mode on.
Functions are called twice then which might be a reason.

I have workaround: https://github.com/openstreetmap-polska/openaedmap-frontend/commit/8b0d70c6a6f63328e2289ffa848e41a941937b88

**Comment by Zaczero** [comment]
I am gonna guess is that the previously used [store](https://www.npmjs.com/package/store) npm package, used some sort of encoding (JSON?) for all values set, so you could pass it [dicts](https://www.npmjs.com/package/store#api), arrays and it would work just fine. With the direct localStorage API use, all values must be strings and thus explicit JSON(?) encoding must be performed to get the same behavior. Because of that, in 2.3 access token strings would be wrapped with " automatically while in 2.4 they are set as-is without any further processing.

**Comment by bhousel** [comment]
Thanks for reporting @starsep , in 44e3703 I added some code similar to your workaround to ignore any double quotes that are wrapping the values.  I tested with my local Rapid and it seems to be ok.
