### ISSUE TITLE
Include warning about insecure usage of cliet secret.

### ISSUE THREAD

**Issue by zdila** [osmlab/osm-auth#51]
This library expect cliet secret to be in the JS which is downloaded to the broser. This is insecure and documetation should at least contain a warning about it.

You can read about it for example at https://oauth1.wp-api.org/docs/advanced/Web.html, chapter _In-Browser Clients_.

**Comment by kamicut** [comment]
@bhousel I think one way to do this is to have a service to proxy requests between the client and the OSM API. Here's how you can do it for [mailgun](https://github.com/jesseditson/mailgun-proxy) or [Prose](https://github.com/prose/gatekeeper) for example. 

The tasking manager is split into client and server, but it splits the auth between [server](https://github.com/hotosm/tasking-manager/blob/develop/server/api/users/authentication_apis.py) and [client](https://github.com/hotosm/tasking-manager/blob/develop/client/app/services/auth.service.js). Since iD does not have a server, to implement the proxy we need to have a separate component and separate deployment. Do you think that's a way we could go?

**Comment by bhousel** [comment]
Hey @kamicut just following up on your question:

> Since iD does not have a server, to implement the proxy we need to have a separate component and separate deployment. Do you think that's a way we could go?

I agree that finding a way to keep the client secrets secure is worth doing..  I'm ok with using an extra proxy layer if it makes apps like iD more secure.

**Comment by bhousel** [comment]
This library and OSM are both based on OAuth2 now.
Going to close this issue since OAuth2 
https://www.oauth.com/oauth2-servers/single-page-apps/
